### ISSUE TITLE
Building firmware missing go-omaha

### ISSUE THREAD

**Issue by GerogeFu** [prusa3d/Prusa-Firmware-SL1#10]
go-omaha-git-r0 do_fetch: Failed to fetch URL git://git@gitlab.com/prusa3d/go-omaha;protocol=ssh;branch=master

**Comment by filipkotoucek** [comment]
Hey. Thanks for the notification. That is part of new update system and the repository was private since new version is not released yet. Anyway, I made it public so you can build it.
