### ISSUE TITLE
API access for automation

### ISSUE THREAD

**Issue by EynErgy** [prusa3d/Prusa-Firmware-SL1#11]
Looking to get some values out of the printer to trigger some actions.
Like taking a picture.

I saw the websocket portion but it uses digest auth and I don't see how to connect in node.js.
I also saw reference to octopi upload api.

So is there an API access and how to connect in node.js?

**Comment by filipkotoucek** [comment]
We are actually migrating to REST with octoprint-like structure. But we will stick to HTTP digest. There are plenty of tutorials how to implement digest with node server. https://dev.to/leolanchas/how-to-implement-http-digest-rfc-2617-in-javascript-in-node-using-passportjs-17l8
