### ISSUE TITLE
Misspelling in web interface

### ISSUE THREAD

**Issue by andrewluebke** [prusa3d/Prusa-Firmware-SL1#14]
In version 1.3.3 the web interface has a misspelling.  It says Printer status: Priting.  Should be Printer status: Printing.

**Comment by filipkotoucek** [comment]
Thanks for the report. This issue will be fixed in next release (1.4.0).

**Comment by filipkotoucek** [comment]
I just wanted to let you know this issue is fixed in out recent rc build https://github.com/prusa3d/Prusa-Firmware-SL1/releases/tag/1.4.0-rc.1. We plan to release the stable build in week or two.

**Comment by andrewluebke** [comment]
Thanks!
