### ISSUE TITLE
1.4.0 RC1 Missing Timezone

### ISSUE THREAD

**Issue by malcinator** [prusa3d/Prusa-Firmware-SL1#17]
Trying to change the Asia Timezone in the Settings Menu gives me no option for either Japan or Tokyo.

**Comment by JakoobCZ** [comment]
Hi, thank you for the feedback, we will take a look at this and extend the list.

**Comment by filipkotoucek** [comment]
We fixed this issue and it will be released with 1.4.1. We expect it in week or two. Thanks for the notice.
