### ISSUE TITLE
1.4.0-RC1 Missing Time Zone - City

### ISSUE THREAD

**Issue by Olefff** [prusa3d/Prusa-Firmware-SL1#18]
UK does not appear in zone list and London no longer appears under Europe. Cannot set location to UK now.

**Comment by JakoobCZ** [comment]
Hi, thanks for the feedback, we will investigate this and add the London back.

**Comment by filipkotoucek** [comment]
We fixed this issue and it will be released with 1.4.1. We expect it in week or two. Thanks for the notice.
