### ISSUE TITLE
Resin levels check not working in 1.4

### ISSUE THREAD

**Issue by jfearnside** [prusa3d/Prusa-Firmware-SL1#21]
I have 35-40% resin in my tank/vat. The resin sensor is turned on in settings. This photo was taken with the tank homed and in the level position. 
![image](https://user-images.githubusercontent.com/29286841/84306547-db98a400-ab18-11ea-8c9f-6a11c302a1fc.png)

I started a print that requires 70% full tank/vat. 
![image](https://user-images.githubusercontent.com/29286841/84306605-ef440a80-ab18-11ea-9109-97ac276a042c.png)

Expected result: Platform should lower for it to perform the resin check and then the SL1 should have warned that there is not enough resin to complete the print and ask if I want to continue. 
Actual result: The platform lowered, measured resin volume, and then the print started with no warning despite there not being enough resin.

**Comment by danielkgore** [comment]
I've experienced the same problem.

**Comment by JakoobCZ** [comment]
The resin sensor algorithm was fixed in the 1.4.1 release, download it via OTA or here https://github.com/prusa3d/Prusa-Firmware-SL1/releases/tag/1.4.1

If the problem persists, please let us know.
