### ISSUE TITLE
Broken build development SD image

### ISSUE THREAD

**Issue by brendhow-done3d** [prusa3d/Prusa-Firmware-SL1#25]
I have problem to build develpment SD image and crash all process in my system, the exit code:

`Prusa-Firmware-SL1/sources/oe-core/meta/recipes-devtools/qemu/qemu-native_4.1.0.bb:do_compile) failed with exit code '1'`

Running on Ubuntu 20.04

**Comment by filipkotoucek** [comment]
Thanks for pointing this out. We fixed it by updating the versions of open embedded components (zeus branch). The fix will be released with version 1.4.2 which we expect in a week or two. We will also build the images from scratch before every release to minimize the risk it will not be buildable for new users.

**Comment by brendhow-done3d** [comment]
Im waiting, thanks for reply !
