### ISSUE TITLE
Read UV calibrator in Windows OS

### ISSUE THREAD

**Issue by rogercorrea** [prusa3d/Prusa-Firmware-SL1#28]
Please,

Do I need read UV calibrator in the Windows OS or Debian to interance with my custom codes to control process of 3D print. 
Do you know as I can read parameters of the sensor without using Prusa firmware?
In Windows the driver identified was the CH-340 that is the USB chipset, but I don't know as communicate with the controller.

Thanks!

**Comment by JakubSilar3D** [comment]
Hi. I think you can safely borrow from https://gitlab.com/prusa3d/sl1/a64-fw/blob/e6a64a032128bcc049cf2af98aff914b2d08a810/sl1fw/libUvLedMeterMulti.py in the opensource ui.
Both the low-level code and the data format produced by the calibrator  can be used there.
