### ISSUE TITLE
Tower homing check failed

### ISSUE THREAD

**Issue by kromeninja** [prusa3d/Prusa-Firmware-SL1#31]
Randomly when starting a print it will fail the preflight check due to the tower homing error, it will only hit the top of the screw 3 times where as a successful preflight tower homing check it hits it four times.

I have tried a factory reset, older/ latest firmware and reduced the tower sensitivity with no luck, it still occurs sadly. The printer was purchased pre assembled and we have confirmed all the screws are tight around that area of the tower.

Prusa forum thread to the same issue:
https://forum.prusaprinters.org/forum/original-prusa-sl1-assembly-and-first-prints-troubleshooting/tower-home-error/#post-374863

**Comment by JakubSilar3D** [comment]
Hi, sorry for the late answer.  A simmilar problem was fixed in 1.5.0. Please try to upgrade. If this does not help, contact support. Github issues are intended to support community opensource development, rather than specific printing problems.
