### ISSUE TITLE
cannot read from remote-api repository

### ISSUE THREAD

**Issue by venny166** [prusa3d/Prusa-Firmware-SL1#32]
The bitbake recipe in Prusa-Firmware-SL1/sources/meta-prusa/recipes-firmware/sl1fw-api/sl1fw-api_git.bb points to prusa3d/SL1/remote-api on Gitlab, which cannot be read from (only an empty folder is visible). Error 403 is returned when trying to read with SSH.
Only remote-api and meta-sl1 are inaccessible. What could be the reason? Surely I am not the only user who tried to build his own customized firmware version.
Any pointers are welcome.

**Comment by JakubSilar3D** [comment]
Hi @venny166, looks like something happened to the rights of the linked project. We are looking into it.

**Comment by JakubSilar3D** [comment]
It the access rights where reallly wrong. The access to sl1fw-api should be OK (public), now. We will test it, but you should be good to go and your verification would help.

**Comment by JakubSilar3D** [comment]
Fixed and tested. Thanks for letting us know.
