### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by malcinator** [prusa3d/Prusa-Firmware-SL1#33]
Having problems connecting to my WiFi Network with V1.5.0.

Plugged Keyboard in to from USB to enter SSID of Wifi Network and found no input from Keyboard.
I see a mouse pointer on screen and the caps lock light illuminates on the keyboard.

I have tested the keyboard on my Computer and all keys are functioning.
![JPEG image](https://user-images.githubusercontent.com/6315804/114295778-483a5180-9ae2-11eb-8d56-3c5afb25c325.jpeg)

**Comment by JakubSilar3D** [comment]
Hi. Thank you for reporting this. I  suppose the workaround - rearranging items on the touchscreen and moving focus to the input line works for you.  We have logged the bug fix it in future v 1.5.1. Feel free to consult support/reopen this  if this impacts your work.
