### ISSUE TITLE
Many errors in the web interface.

### ISSUE THREAD

**Issue by flandaluce** [prusa3d/Prusa-Firmware-SL1#34]
When you access the printer control via IP, it does not correctly indicate a lot of data, remaining time, printing time, host name, remaining resin, etc ... and the print image does not appear.

I am attaching a screen.

<img width="1254" alt="Captura de Pantalla 2021-05-07 a la(s) 21 10 30" src="https://user-images.githubusercontent.com/1781710/117522403-c7536600-af78-11eb-9e4f-35c139cdfeca.png">

**Comment by JakubSilar3D** [comment]
Hi. Thanks for your attention. Just to clarify, what firmware version are you using?

**Comment by flandaluce** [comment]
Version 1.5.0

**Comment by JakubSilar3D** [comment]
These are known issues in 1.5.0. The Prusa Link (new name for Prusa Local connect) web interface will be much better in 1.6.0 which is due in several weeks. You can get it earlier by joining the beta tester group. 
But the 1.6.0 is a big rework of the firmware internals, so all the usual beta disclaimers will apply.

**Comment by JakubSilar3D** [comment]
Most of the things you mention are fixed in 1.6.0 which has been just released.
