### ISSUE TITLE
Unable to upgrade firmware from internet

### ISSUE THREAD

**Issue by andrewluebke** [prusa3d/Prusa-Firmware-SL1#48]
I can't get the printer to recognize that there are new versions of the firmware available on the internet.  The last version that automatically upgraded was 1.6.0.  I had to upgrade to 1.6.1 manually with USB and 1.6.2 isn't showing up either.  The log shows
Aug 26 11:12:48.042560 SL1S-6.customccc.com touch-ui[294]: qml: Initating manual check for update
Aug 26 11:12:48.045179 SL1S-6.customccc.com updater[301]: 2021-08-26 11:12:48.045034307-07:00  DEBUG Checking for a new version as requested by ondemandupdate.
Aug 26 11:12:48.157077 SL1S-6.customccc.com updater[301]: 2021-08-26 11:12:48.156984348-07:00   INFO No update is currently available.
Aug 26 11:12:48.157651 SL1S-6.customccc.com updater[301]: 2021-08-26 11:12:48.157102265-07:00   INFO Scheduled next check in 48m13s.

It seems unlikely that the firmware check would only take about 100ms to come back.

I also see the printer trying to go to https://update.prusa3d.com/service/update2 unsuccessfully.  When I try to go there manually I get an empty webpage.  Not sure if that is related.

**Comment by Area5142** [comment]
I'm having the exact same problem, just tried to upgrade from 1.6.1 to 1.6.2 from the Internet.
Like @andrewluebke, I did the upgrade from 1.6.0 to 1.6.1 with download and USB stick.

**Comment by andrewluebke** [comment]
This seems to have been resolved on the other side since I was able to upgrade from 1.6.1 to 1.6.3 today on all of my printers.  Everyone else working too?  If so I'll close this.

**Comment by Area5142** [comment]
Same here, I just updated from 1.6.1 to 1.6.3 from the Internet.
