### ISSUE TITLE
Resin Calibration Object for SL1S

### ISSUE THREAD

**Issue by Undermeadow1** [prusa3d/Prusa-Firmware-SL1#49]
There are no resin calibration objects after downloading the examples in the new SL1S Speed version.

**Comment by andrewluebke** [comment]
Yes I saw the same thing.  I wanted to calibrate with some exotic resin and couldn't.

**Comment by achingbrain** [comment]
Not in `v1.6.3` either.

@filipkotoucek @zavorka @vladamatena any ideas when the ability to calibrate new resins will be added?

**Comment by Jerzinek** [comment]
Hi, we are working on this feature fix. I believe it is a matter of several weeks. Please stay tuned.

**Comment by VavoSam** [comment]
Hi, when will be this feature ready?

**Comment by Area5142** [comment]
Is Resin Calibration Object part of the newly released 1.6.4 version?

**Comment by Jerzinek** [comment]
Not yet, Unfortunately. We are still working on this feature fix.  It
should be released hopefully very soon after the New Year. Apologize for
the inconvenience.

st 22. 12. 2021 v 13:03 odesílatel Joakim Hjort ***@***.***>
napsal:

**Comment by Hauzman** [comment]
Hi is there a way to calibrate rasin until you release the official one.

**Comment by Undermeadow1** [comment]
Yes there is unofficial and seems to work well:
[Resin Calibration SL1S.zip](https://github.com/prusa3d/Prusa-Firmware-SL1/files/7887882/Resin.Calibration.SL1S.zip)

**Comment by Hauzman** [comment]
> Yes there is unofficial and seems to work well:
> [Resin Calibration SL1S.zip](https://github.com/prusa3d/Prusa-Firmware-SL1/files/7887882/Resin.Calibration.SL1S.zip)
> 

Thank you I will try it out this day's and let you you know.
I need to calibrate some biocompatible materials

**Comment by Hauzman** [comment]
> Yes there is unofficial and seems to work well:
> [Resin Calibration SL1S.zip](https://github.com/prusa3d/Prusa-Firmware-SL1/files/7887882/Resin.Calibration.SL1S.zip)
> 

@Undermeadow1 I can confirm it's working I will make also for the flex resin i use ![20220121_093311.jpg](https://user-images.githubusercontent.com/56076331/150485756-45a6251e-1cae-4ee1-bf5c-bf6a2c25e269.jpg)![20220121_093304.jpg](https://user-images.githubusercontent.com/56076331/150485762-aaa716b7-b9f3-4de5-aa6d-d493e7628f83.jpg)

**Comment by Prusa-Support** [comment]
Hello Guys, 

thank you very much for your patience! 
The Resin Calibration Objects are about to be in the Stable version, you can already use this feature in the [1.7.0-beta.4] and also try the Resin tank cleaning feature, your feedback on this will be appreciated. Please open a new issue if there is anything as this topic will be closed for now

Sarah Kapodistria 
Prusa Research

**Comment by achingbrain** [comment]
I've just tried the calibration print in the beta firmware, it works well, thanks so much!
