### ISSUE TITLE
Feature Request - Ability to delete all files or some portion of files

### ISSUE THREAD

**Issue by andrewluebke** [prusa3d/Prusa-Firmware-SL1#50]
It would be very useful to be able to mass delete files from the printers storage.  Especially with the new swipe right to start print I don't have an easy opportunity to delete the last file I printed.  So either a delete all or multiple selection option would be nice.  Thanks...

**Comment by Prusa-Support** [comment]
Thank you for your suggestion! We will add this to our feedback and see if it can be implemented in the future.
The only option currently is to go to the project overview and swipe the file to the left and delete them one by one before the memory is full.

Sarah Kapodistria
Prusa Research
