### ISSUE TITLE
Feature Request: Vat cleaning function

### ISSUE THREAD

**Issue by DAVEfromCZE** [prusa3d/Prusa-Firmware-SL1#54]
It would be great to have a cleaning function. If multiple objects are printed and several or all of them peel off, cleaning from FEP film is difficult. If one whole layer is cured for at least 30 seconds, it is possible to carefully peel off a part of the cured layer from the underside of the FEP foil and then peel it off with the peel-off prints. I suggest adding a function where the Z axis is parked upwards, the platform is taken down and the whole layer is hardened.

**Comment by Prusa-Support** [comment]
Hello, 

thank you for the suggestion!
Your wish has been heard :) 
Please check out our 1.7.0 beta version https://github.com/prusa3d/Prusa-Firmware-SL1/releases
Feel free to test and let us know about your experience

Best regards,
