### ISSUE TITLE
Tower homing error

### ISSUE THREAD

**Issue by JPElectron** [prusa3d/Prusa-Firmware-SL1#56]
When starting a new print, tower cannot home.  See additional reports of this error in the forum posts...

https://forum.prusaprinters.org/forum/original-prusa-sl1-assembly-and-first-prints-troubleshooting/tower-home-error/

and

https://forum.prusaprinters.org/forum/original-prusa-sl1-hardware-firmware-and-software-help/starting-a-new-print-results-in-failure/

**Comment by Prusa-Support** [comment]
Hello, 
thank you for the report! Usually, it helps if you adjust the platform axis sensitivity to either + or - maximum 2 in the settings. 
If that does not help, please contact our Tech Support via 24/7 LiveChat or Email and they can help you for sure

Best regards,

Sarah Kapodistria
Prusa Research
