### ISSUE TITLE
Can't delete a (bad) file from the printer

### ISSUE THREAD

**Issue by JPElectron** [prusa3d/Prusa-Firmware-SL1#57]
If a file uploaded to the printer is "bad" there is no way to delete it since the file is never able to load, you don't get the option to delete it.

Additional information in the forum post: https://forum.prusaprinters.org/forum/original-prusa-sl1-hardware-firmware-and-software-help/cant-delete-a-file/

**Comment by Prusa-Support** [comment]
Hello, 
thank you for the report! Just to be sure, you're going to the print file overview and you try to swipe on the print you would like to delete but it offers no delete option but for other successful uploads it does? 
If that's the case, could you please send us a short video of the problem to the official tech support email and attach the log file as well? 

Best regards

**Comment by JPElectron** [comment]
Video showing how I can't delete bad files...
https://www.youtube.com/watch?v=sSIbl8vRTLc

Also not possible from the printer screen.

**Comment by Prusa-Support** [comment]
Thank you for the video! Unfortunately, this is connected to PrusaLink and not directly to the printer.
We tested the last FW versions and it seems to work for us.
Please send us more information about how a file can't be deleted from the printer, preferably via email at info@prusa3d.com with the log file attached and you can ask me directly, I will be happy to help 

Sarah Kapodistria
Prusa Research
