### ISSUE TITLE
Missing Calibration Object SL1S

### ISSUE THREAD

**Issue by ndawghoodstar** [prusa3d/Prusa-Firmware-SL1#58]
Please add the resin exposure time calibration utility to SL1S

**Comment by Area5142** [comment]
Related to #49.

**Comment by Prusa-Support** [comment]
Thank you for your patience, the Resin Calibration Objects are about to be in the Stable version, you can already try this feature in the [1.7.0-beta.4]. Please open a new issue if there is anything as this topic will be closed for now

Sarah Kapodistria
Prusa Research
