### ISSUE TITLE
Feature Request: Erase internal memory

### ISSUE THREAD

**Issue by ndawghoodstar** [prusa3d/Prusa-Firmware-SL1#59]
Please add ability to delete all files once internal memory is full.

**Comment by andrewluebke** [comment]
Related to #50

**Comment by Prusa-Support** [comment]
Thank you for your suggestion! We will add this to our feedback and see if it can be implemented in the future.
The only option currently is to go to the project overview and swipe the file to the left and delete them one by one before the memory is full.

Sarah Kapodistria
Prusa Research
