### ISSUE TITLE
NEED a Resin Exposure Finder for SL1

### ISSUE THREAD

**Issue by mylife4aiurr** [prusa3d/Prusa-Firmware-SL1#6]
Day 1 purchaser of SL1.  

There are countless brands of resin that respond to 405nm light. I thank Prusa for making profiles for some of the other popular brands besides Prusa's own resin. 
Recently I have started trying to use other brands of resin. Currently I have to test one exposure per session on SL1. Testing 1 exposure per session is time consuming and expensive. 
Several other manufacturers have a gcode instruction that test several different exposure times on a single buildplate during a single print session. So a user can find good bottom layer and per layer times quickly and efficiently. Something like this used internally? We need a similar tool for SL1 - please. 

In the photo Im testing two different exposure times with a white resin on lithophanes, I dont know if the photo is accurate enough but farther testing is required and i'll have to do it one print at a time. Wasting time and resin in the process.
![20191013_113803 (1)](https://user-images.githubusercontent.com/31583073/66718121-59e84f00-edae-11e9-8dd7-abc9c777c4e6.jpg)

In this photo I got the x and y dimensions accurate with elegoo green but circles not so much
![20191006_132935 (1)](https://user-images.githubusercontent.com/31583073/66718237-910b3000-edaf-11e9-9975-130e6acd840c.jpg)

**Comment by mylife4aiurr** [comment]
![20191013_143815](https://user-images.githubusercontent.com/31583073/66720243-3cc07a00-edc8-11e9-8749-e511163ec2ad.jpg)
7.0s per layer
7.5s per layer
8.0s per layer

**Comment by mylife4aiurr** [comment]
Thanks to cerium136 over on prusa forums
https://forum.prusaprinters.org/wp-content/uploads/2019/10/SL1_Resin_Calibration_Mode.pdf

Found out there is a capability in sl1's firmware. Use at your on risk but him and I have been trying to figure out how to use it. Still would love some official guidance.

**Comment by mylife4aiurr** [comment]
Hi

**Comment by mylife4aiurr** [comment]
Any response from Prusa on this?

**Comment by michalxfanta** [comment]
We prepare this feature with a description of how to use it and with a procedure on how to find correct exposure time for tested resin, in some of the next releases.

**Comment by mylife4aiurr** [comment]
Ok that's all I wanted was a response and acknowledgement

**Comment by X3msnake** [comment]
https://www.facebook.com/Photonsters/posts/932832370504077

**Comment by X3msnake** [comment]
@michalxfanta why did the Prusa team opted out for using standard Gcode?

**Comment by filipkotoucek** [comment]
https://github.com/prusa3d/Prusa-Firmware-SL1/issues/8#issuecomment-574888377

**Comment by mylife4aiurr** [comment]
How do we calibrate initial exposure time??
I've asked here:
https://help.prusa3d.com/en/article/sl1-resin-calibration-object_112182

and here also in the comments:
https://youtu.be/_rRCGzKNTxc
