### ISSUE TITLE
Self test failure with 1.6.6 - rear fan RPM issue

### ISSUE THREAD

**Issue by sovcharenko** [prusa3d/Prusa-Firmware-SL1#60]
It looks like 1.6.6 is not backward compatible with old HW.

Upgraded to  1.6.6, ran self test - Rear fan RPM not in range error, can't print anything
Downgraded to 1.6.4, self test successful.

SL1S was delivered in Feb 2022

**Comment by JakubSilar3D** [comment]
Thanks for reporting this. Can you, pls. contact support and provide them with the logs.

**Comment by Prusa-Support** [comment]
Hello, 
unfortunately, we couldn't register a ticket about this issue. Feel free to contact me with the log via info@prusa3d.com if you're still facing issues, otherwise, this topic will be closed

Sarah Kapodistria
Prusa Research
