### ISSUE TITLE
Feature request: Power on/off options

### ISSUE THREAD

**Issue by khenderick** [prusa3d/Prusa-Firmware-SL1#62]
I would like to request 2 power-related features:
* As far as I understand, the SL1S is running some kind of embedded linux. This would mean that turning it off via the switch at the back would not be a good thing regarding to file system corruption etc. Therefore, it would be nice to be able to power down the printer over the API. The current auto-power-off feature seems to be turning off the printer immediately after the print completes.
* It would also be nice to set the printer to auto-power-on, so when the switch at the back is turned on, the printer starts automatically.

My practical use case: 

I monitor my printer remotely, and my printer is connected to a remotely controllable socket. When the print completes, I get a notification with some stats. When I activate the auto-power-off feature, the printer turns off too soon, so my scripts can't reliable detect a finished print. The power-off API would allow my script to notice the print has finished, collect the desired information, send the notification, turn off the printer, and after a minute or so power down the socket.
When I'm about to make a new print, I can remotely turn on the socket after which the printer automatically starts. I can then use the web interface to upload a file, and then go to the printer to physically start the print.

**Comment by JakubSilar3D** [comment]
Both ideas sound nice. Thanks.
This switch off over api is in the backlog /no promises/.
There is no reasonable way to implement the "auto-power-on" on SL1s hardware, unfortunately.
